# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
    - ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
    - ps: Bootstrap
    - ps: mkdir -Force c:\deps
    - ps: >-
        if (-Not (Test-Path C:\deps\openms.exe)) {
            Invoke-WebRequest https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/2.5.0/OpenMS-2.5.0-Win64.exe -OutFile "C:\deps\openms.exe"
        }
        C:\deps\openms.exe /S
    - ps: >-
        if (-Not (Test-Path C:\deps\MetFrag2.4.5-CL.jar)) {
            Invoke-WebRequest http://msbi.ipb-halle.de/~cruttkie/metfrag/MetFrag2.4.5-CL.jar -OutFile "C:\deps\MetFrag2.4.5-CL.jar"
        }
    - ps: >-
        if (-Not (Test-Path C:\deps\sirius-win64-headless-4.4.23)) {
            Invoke-WebRequest https://bio.informatik.uni-jena.de/repository/dist-release-local/de/unijena/bioinf/ms/sirius/4.4.23/sirius-4.4.23-win64-headless.zip -OutFile "C:\deps\sirius-win.zip"
            7z x -oC:\deps\ C:\deps\sirius-win.zip
        }
    - ps: >-
        if (-Not (Test-Path C:\deps\openbabel.exe)) {
            Invoke-WebRequest https://github.com/openbabel/openbabel/releases/download/openbabel-3-0-0/OpenBabel-3.0.0.exe -OutFile "C:\deps\openbabel.exe"
        }
        C:\deps\openbabel.exe /S


    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

cache:
  - C:\RLibrary
  - C:\Program Files\Pandoc\
  - C:\deps

# Adapt as necessary starting from here

# Install Pandoc: https://github.com/krlmlr/r-appveyor/issues/82#issuecomment-261695154
before_test:
  - ps: >-
      if (-Not (Test-Path "C:\Program Files\Pandoc\")) {
        cinst pandoc
      }
  - ps: $env:Path += ";C:\Program Files\Pandoc\"
  - pandoc -v
  - ps: >-
      if (-Not (Test-Path "C:\ProgramData\chocolatey\bin\pngquant.exe")) {
        cinst pngquant --ignore-checksums
      }

platform: x64
environment:
    R_ARCH: x64
    BIOC_USE_DEVEL: FALSE
    _R_CHECK_FORCE_SUGGESTS_: FALSE
    R_CHECK_ARGS: --no-build-vignettes --no-manual --no-multiarch
    av_token:
      secure: JJT6ZdxNWo6wf+xPRwfOXAXW1M65jtdzRXCKFGarzzQ=

build_script:
    - travis-tool.sh install_r tibble # workaround for MSnbase
    - travis-tool.sh install_bioc mzR xcms CAMERA Rdisop
    - travis-tool.sh install_github rickhelmus/patRoonData
    - travis-tool.sh install_github blosloos/nontarget
    - travis-tool.sh install_github cbroeckl/RAMClustR
    - travis-tool.sh install_r vdiffr
    - travis-tool.sh install_r covr
    - travis-tool.sh install_deps

test_script:
    - set JAVA_HOME=C:\PROGRA~1\Java\jdk11
    - set PATH=%JAVA_HOME%\bin;C:\Program Files\OpenMS-2.5.0\bin;C:\Program Files\OpenBabel-3.0.0;%PATH%
    - set OPENMS_DATA_PATH=C:\Program Files\OpenMS-2.5.0\share\OpenMS
    - set PATROON_METFRAG=C:\deps\MetFrag2.4.5-CL.jar
    - set PATROON_SIRIUS=C:\deps\sirius-win64-headless-4.4.23
    - set PATROON_JUNIT=%APPVEYOR_BUILD_FOLDER%\junit.xml
    # HACK for SIRIUS
    - del C:\tools\Coverity\bin\jnidispatch.dll
    - travis-tool.sh run_tests

on_failure:
    - if exist %APPVEYOR_BUILD_FOLDER%\junit.xml ( type %APPVEYOR_BUILD_FOLDER%\junit.xml && appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\junit.xml )
    - 7z a failure.zip *.Rcheck\* "-xr!*.sqlite"
    - appveyor PushArtifact failure.zip

on_success:
  # NOTE: disable coverage compiler flags as they don't work with GenForm
  - Rscript -e "options(covr.flags = list(CXXFLAGS = '', LDFLAGS = '')); covr::codecov()"
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "master") { .\av_trigger_deps.ps1 }

on_finish:
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", "$($env:PATROON_JUNIT)")

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
